# Generated by Django 3.2.5 on 2022-03-26 09:32

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'user',
            },
            managers=[
                ('manager', articles.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(default='domestic', max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('noun', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_ids', models.TextField()),
                ('good_nouns', models.TextField()),
                ('recommended_id_rate_pair', models.TextField()),
                ('uninterested_ids', models.TextField()),
                ('uninterested_nouns', models.TextField()),
                ('rejected_id_rate_pair', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
