# Generated by Django 3.2.5 on 2022-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
