version: '3'
services:
  db:
    image: mysql:8.0
    command: --default_authentication_plugin=mysql_native_password
    env_file:
      - ./.mysql_env
  web:
    build: .
    # image: continuumio/miniconda3:latest
    # command: python django/manage.py runserver 0.0.0.0:8000
    # command: 
    # env_file:
    #   - ./.django_env
    volumes:
      - .:/code
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - db