version: '3'
services:
  db:
    image: mysql:8.0
    command: --default_authentication_plugin=mysql_native_password
    env_file:
      - ./.mysql_env
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - db
#     networks:
#       application_net:
#         ipv4_address: 172.20.0.3
# networks:
#   application_net:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16
