version: '3'
services:
  db:
    image: mysql:8.0
    env_file:
      - ./.mysql_env
    command: >
      /bin/bash -c "--default_authentication_plugin=mysql_native_password && 
      echo "GRANT ALL PRIVILEGES ON test_django_db.* TO 'django'@'%';" | 
      mysql -u root -p $MYSQL_ROOT_PASSWORD"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - db
