version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build_and_test:
    machine: true
    working_directory: ~/nouns-matched-articles
    steps:
      - checkout
      - run:
          name: setup mysql env values
          command: echo $MYSQL_ENV_VARS | base64 --decode > .mysql_env
      - run:
          name: setup django env values
          command: echo $DJANGO_ENV_VARS | base64 --decode > .django_env 
      - run:
          name: compose up db
          command: docker-compose up -d db
      - run:
          name: migrate
          command: docker-compose run web /bin/bash -c "export DB_LOCALHOST=127.0.0.1 && env && python django/manage.py migrate"
      - run:
          name: test
          command: docker-compose run web /bin/bash -c 'cd django && python manage.py test'
      - run:
          name: compose down
          command: docker-compose down
workflows:
  build_and_test_flow:
    jobs: 
      - build_and_test
#       - test: 
#           requires:
#             - build_and_test
