version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build_and_test:
    machine: true
    working_directory: ~/nouns-matched-articles
    steps:
      - checkout
      - run:
          name: install Dockerize
          command: sudo apt-get update && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.5.0
      - run:
          name: setup mysql env values
          command: echo $MYSQL_ENV_VARS | base64 --decode > .mysql_env
      - run:
          name: setup django env values
          command: echo $DJANGO_ENV_VARS | base64 --decode > .django_env 
      - run:
          name: docker build
          command: docker-compose build
      - run:
          name: compose up db
          command: docker-compose up -d db
          # environment:
          #   MYSQL_HOST: 127.0.0.1
      # - run:
      #     name: waiting for launch db
      #     command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: waiting for launch db
          command: sleep 20
      # - run:
      #     name: migrate
      #     command: docker-compose run web /bin/bash -c "export DB_LOCALHOST=127.0.0.1 && env && python django/manage.py migrate"
      - run:
          name: migrate
          command: docker-compose run web bash -c "python django/manage.py migrate"
      - run:
          name: test
          command: docker-compose run web /bin/bash -c 'cd django && python manage.py test'
      - run:
          name: compose down
          command: docker-compose down
workflows:
  build_and_test_flow:
    jobs: 
      - build_and_test
#       - test: 
#           requires:
#             - build_and_test
