version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/nouns-matched-articles/django
    steps:
      - checkout
#       - python/install-packages:
#           pkg-manager: pip
      - run:
          name: Run tests
#           command: pytest
          command: echo "Hello, world!"
#   test:
#     docker:
#       - image: 
workflows:
  build_and_test:
    jobs: 
      - build
#       - test: 
#           requires:
#             - build
