version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    # docker:
    #   - image: cimg/python:3.9
    working_directory: ~/nouns-matched-articles
    steps:
      - checkout
#       - python/install-packages:
#           pkg-manager: pip
      # - run:
          # name: Run tests
#           command: pytest
          # command: echo "Hello, world!"
      - run:
          name: setup env values
          command: echo $ENV_VARS | base64 --decode > .mysql_env
      - run:
          name: compose up
          command: docker-compose up -d db
      - run:
          name: waiting
          command: sleep 10
      - run:
          name: migrate
          command: docker-compose run web python django/manage.py migrate
      - run:
          name: test
          command: docker-compose run web python django/mange.py test
      - run:
          name: compose down
          command: docker-compose down
#   test:
#     docker:
#       - image: 
workflows:
  build_and_test:
    jobs: 
      - build
#       - test: 
#           requires:
#             - build
